CREATE TABLE rules (
    id TEXT PRIMARY KEY NOT NULL,
    account_id TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL,
    description TEXT NOT NULL,
    "references" TEXT NOT NULL,
    tags TEXT NOT NULL,
    author TEXT NOT NULL,
    date TEXT NOT NULL,
    logsource TEXT NOT NULL,
    detection TEXT NOT NULL,
    fields TEXT NOT NULL,
    falsepositives TEXT NOT NULL,
    level TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
);